### ISSUE TITLE
Add new UGRID config from MET to METplus Wrappers

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#2501] opened 2024-02-15 18:48 UTC
## Describe the Enhancement ##
After dtcenter/MET#2231, there are new MET configuration file options that are not currently supported in METplus Wrappers. The configuration file options are here:

https://github.com/dtcenter/MET/blob/afb45764185bb280bacaf134ae191c6b39d041a9/data/config/PointStatConfig_default#L300-L306

and here:
https://github.com/dtcenter/MET/blob/afb45764185bb280bacaf134ae191c6b39d041a9/data/config/GridStatConfig_default#L265-L271

The work is to add six new config options to METplus Wrappers:
```
POINT_STAT_UGRID_DATASET
POINT_STAT_UGRID_MAX_DISTANCE_KM
POINT_STAT_UGRID_COORDINATES_FILE
GRID_STAT_UGRID_DATASET
GRID_STAT_UGRID_MAX_DISTANCE_KM
GRID_STAT_UGRID_COORDINATES_FILE
```

Note that there are also two new UGRID config files in the MET repo. I am unclear at this time how these relate to METplus Wrappers, but I will use `METPLUS_MET_CONFIG_OVERRIDES` to set the above items for now and see if these new UGRID config files cause trouble with METplus Wrappers. I will update this issue with more details soon.

Update: The new UGRID capability works by setting `POINT_STAT_MET_CONFIG_OVERRIDES` so there is no additional work for the new UGRID config files beyond supporting the new conf items.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment] 2024-02-15 19:30
FYI @willmayfield

**Comment by georgemccabe** [comment] 2024-02-15 19:57
This is a duplicate of #2433. In that issue, I asked for clarification of the names of the new config variables and did not receive a response. See the discussion on that issue and let me know how to proceed.

**Comment by DanielAdriaansen** [comment] 2024-02-15 20:06
Thanks @georgemccabe sorry for the duplication.

**Closed as not planned** 2024-02-15 20:06 UTC
Labels: type: enhancement, alert: NEED ACCOUNT KEY, METplus: Configuration
