### ISSUE TITLE
Logging - confirm error message not sent to tty or logfile

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#113] opened 2018-08-31 16:30 UTC
Minna brought up the following logging issue.  

When working with Perry, there was an ERROR Generated FROM A MET EXECUTABLE where a directory did not exist that was required.  However,  the error message didn't show up in the log file or the terminal output.

Looking at the code shows the current logic should catch this ... so this behavior needs to be recreated ....

To be certain ... this test will recreate the behavior from both an external MET executable error complaint as well as from the python scripts missing a directory complaint .... 

Setup a test   ... see if faulty behavior can be reproduced and if so  ... fix it.

**Comment by georgemccabe** [comment] 2021-06-02 16:25
Duplicate of #229

**Closed by georgemccabe** 2021-06-02 16:25 UTC
Labels: type: bug
