### ISSUE TITLE
Fix CyclonePlotter cartopy mapping issues

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#850] opened 2021-03-19 16:18 UTC
## Describe the Problem ##
*When plotting the MET tc output in the CyclonePlotterWrapper, the points are in the incorrect location when the map is changed from the default central longitude of 0 degrees to 180 degrees. NOTE/BEWARE: Due to the nature of Cartopy, some of the original syntax employed when Basemap was used may no longer apply, breaking some of the original code. The watermark is no longer appearing on the plot.*

### Expected Behavior ###
*Data for the northern hemisphere should have storm tracks that are over North America and the Pacific Ocean*
![20201007](https://user-images.githubusercontent.com/3753118/111814102-b141f700-889f-11eb-8476-8323e584b224.png)

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)* Mac laptop
*2. OS: (e.g. RedHat Linux, MacOS)* MacOS
*3. Software version number(s)* Python 3.6.3, Matplotlib 3.3.1, 

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Obtain tc pairs output data from 20201007 for NAM 
*2. Get clone of METplus source code
*3. Follow the instructions in the User's Guide for running the CyclonePlotter use case:
https://dtcenter.github.io/METplus/latest/generated/met_tool_wrapper/index.html#cyclone-plotter

*Post relevant sample data following these instructions:*
Set the following values in the CyclonePlotter.conf file (for the use case):

- CYCLONE_PLOTTER_INIT_DATE = 20201007
- CYCLONE_PLOTTER_INIT_HR = 00 ;; hh format
- CYCLONE_PLOTTER_MODEL = NAM
- set font sizes, resolution to customize

### Relevant Deadlines ###
NONE

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** Minna
- [x] Select **scientist(s)** John Opatz

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [x] Fix the bug and test your changes.
- [x] Add/update log messages for easier debugging. Not Avail
- [x] Add/update unit tests. Not Avail
- [x] Add/update documentation. Internal changes no impact to docs
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [x] Close this issue.

**Comment by bikegeek** [comment] 2021-03-19 17:28
As a result of using the PlateCarree projection with a central meridian of 180 (default is 0 degrees), the cyclone track points were getting plotted in the incorrect continent (Eurasia vs North America) because some settings needed to be explicitly defined. 
- fixed the plotting of points in the wrong continent by explicitly setting the transformation via transform=ccrs.PlateCarree() in the plt.plot(xxx) and plt.scatter(xyz) signatures
- added ax.set_global() to fix the map to world view.  If this isn't set, the map zooms in to the region where there are points
- explicitly call the rescale_lon() to ensure that longitudes are in the -180 to 180 scale
- move the watermark so it is no longer obscured by the legend box
- fix the annotations, the original syntax plt.annotate() no longer works when using the transform=ccrs.PlateCarree() syntax, replace with plt.text()
- remove unused static method that was used in the Basemap implementation but not needed for the Cartopy implementation
- updated comments where appropriate

**Comment by georgemccabe** [comment] 2021-03-24 23:45
The changes for the issue broke the regression tests because a watermark with the current time now appears on the output images. This means that the images will be different for every single test and cause a failure. A new PR was added to make the watermark optional (default is to add it) so these tests can pass.

**Comment by j-opatz** [comment] 2021-03-29 22:15
Linked PR #854 has fixed the broken regression tests and we can now close this.

**Closed as completed by j-opatz** 2021-03-29 22:15 UTC
Labels: type: bug, component: graphics, priority: high, requestor: NOAA/EMC, requestor: NOAA/other, requestor: METplus Team
