### ISSUE TITLE
Read MODE-TD "Track" from .stat file

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplus#37] opened 2017-07-19 21:10 UTC
It would be good to have Feature Relative MET+ capability read MODE-TD (MTD) centroid lat/lon pairs, essentially tracks.  Options are:
1) Write a reformatter to write MTD  in an ATCF file format
2) Update the script that reads ATCF files to optionally read MTD tracks

Actually, it might be worth it to do both so people who don't want an additional file can just read MTD output directly

Will attach appropriate MTD output file soon

**Comment by georgemccabe** [comment] 2021-06-02 16:21
This is a duplicate of #641.

**Closed by georgemccabe** 2021-06-02 16:21 UTC
