### ISSUE TITLE
Update the TC-Diag wrapper to support updates for MET version 12.0.0

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2340] opened 2023-09-11 19:50 UTC
## Describe the Enhancement ##
The TC-Diag tool in MET is being updated considerably for MET version 12.0.0. Some of these enhancements impact the TC-Diag METplus wrapper. This issue is enhance that wrapper as needed, and described below. Rather than creating separate issues for each change, I'm bundling them together into this single issue and assigning it to the beta3 development cycle. If it is more convenient to actually make the changes as we go, please feel free to close this issue, and I'll create a new one for additional changes.

List of changes:
1. PR dtcenter/MET#2680 for issue dtcenter/MET#2609:
  - Adds new `one_time_per_file_flag` boolean option to the TC-Diag configuration file. Default is `TRUE`.
  - Modifies the `TCDiagConfig_default` from using "all" lead times found in the tracks (`lead = [];`) to explicitly listing the expected ones:
```
lead       = [   "0",   "6",  "12",  "18",  "24",
                "30",  "36",  "42",  "48",  "54",
                "60",  "66",  "72",  "78",  "84",
                "90",  "96", "102", "108", "114",
               "120", "126" ];
```

### Time Estimate ###
1 day?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2770043

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No additional impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment] 2023-10-04 20:03
Closing this issue since the changes described in this issue were completed with PR #2374. This issue can be reopened as needed if new changes to the MET tool require changes to the METplus wrappers.

**Comment by georgemccabe** [comment] 2023-10-04 21:07
In a TC-Diag meeting on 2023-10-04, we discussed adding new variables under domain_info. @JohnHalleyGotway will update this issue with the details when the names of the new variables are confirmed.

**Closed as completed** 2023-10-16 16:40 UTC
Labels: type: enhancement, component: python wrapper, priority: blocker, requestor: METplus Team, required: FOR OFFICIAL RELEASE, MET: Tropical Cyclone Tools, METplus: Tropical/Extra-Tropical Cyclone
